spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Set to true to see SQL statements in the console
  # Other Spring Boot application properties

server:
  port: 8080 # Change the port if needed
